### ISSUE TITLE
Shipping Zones UI

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#1063]
Shop >> Billables >> Shipping (top menu)

- [x] IndexShippingZoneSchemas (image 1)
- [x] ShowShippingZomeSchema
- [x] EditShippingZoneSchema (only name can be edited)
- [x] IndexShippingZones (image 2)
- [x] EditShippingZone. (change Territories /Prices)

it should look like:

<img width="1268" alt="Screenshot 2024-10-18 at 11 07 47" src="https://github.com/user-attachments/assets/52cb9c3a-3836-458c-a941-045146c81f72">

<img width="1256" alt="Screenshot 2024-10-18 at 11 06 45" src="https://github.com/user-attachments/assets/5ea850a2-fd1a-4ff9-beed-ea38ad6bf9b0">

**Comment by KirinZero0** [comment]
@aqordeon i need you to do smthn abt the ui
