### ISSUE TITLE
New Pallet Delivery can not be created if Customer don't have a valid RentalAgreement

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#112]
- [x] need to modify `function authorize` in the corresponding Store... Action to not allow creation is $fulfilmentCustomer->rentalAgrement is null or expired renta_agreement.state <-- this Enum, table columen need to be created  
- [x] In aiku UI
- [x] In retina UI 

We need to give some kind of feedback why a Pallet delivery can not be created, e.g. buttoon still there but disabled and a model will pop up with some text explaining what to do , we will discuse the text content after modal works

**Comment by inikoo** [comment]
RentalAgreementStateEnum changed  
    case DRAFT              = 'draft';
    case ACTIVE             = 'active';
    case EXPIRED            = 'expired';

**Comment by YudhistiraA** [comment]
hello @inikoo 

![image](https://github.com/inikoo/aiku/assets/42015612/90f83cae-e26b-4fa0-9fac-279afc2203b6)


i already create the modal for that , 
you can edit the text in this file :  Components/Tables/Grp/Org/Fulfilment/TablePalletDeliveries.vue
