### ISSUE TITLE
Pallet limits logic

### ISSUE THREAD

**Issue by itzArtha** [inikoo/aiku#114]
in Retina, if the number of stored pallets + pallets in the pallet delivery been created by customers <  pallet limits. the customer when click [ submit]. we will call Confirm (Submit+conform) but if  pallet limits is null or  stored pallets + pallets > limit , that [Submit] button will call Submit action only
then in aike, if  pallet limits is set and is exceed we shoudl print a warnign top of. pallet delivery been created, and in the ShowFulfulmentCutomer
work in this i just write above

**Comment by YudhistiraA** [comment]
hello @itzArtha 

![image](https://github.com/inikoo/aiku/assets/42015612/bea4888c-8f33-489d-ad04-51e732443732)

done
