### ISSUE TITLE
Homologate href => route  arguments

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#1202]
forget href the official argument name is **route**
<img width="603" alt="Screenshot 2024-11-13 at 14 09 30" src="https://github.com/user-attachments/assets/c676a850-955b-4736-a922-abf48428eae4">

**Comment by aqordeon** [comment]
Commit: https://github.com/inikoo/aiku/commit/9fb1693a17dcd350292b850366e2891376b4d243
