### ISSUE TITLE
Wrap  (shops, fulfilments, 🎊 digital marketing ) menus into a common block

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#13]
<img width="270" alt="Screenshot 2024-04-06 at 13 56 50" src="https://github.com/inikoo/aiku/assets/8298090/3e25378e-fbc5-4c1f-bd2a-342035625c13">

- [x] It should show only one shops at a time
- [x] The items inside block can not be compacted (remove ^)
- [x] In the heather the Shop code should be more prominent (bigger font). 
- [x] In header should be navigation arrows.(FA icons) . < ^ >  no go to prev/next shop ^ will go to a new Shops blocks, the items for this  will be given from the BE

**Comment by aqordeon** [comment]
elaborate more about point of this two
> `It should show only one shops at a time`

> and `< ^ > no go to prev/next shop ^ will go to a new Shops blocks`
