### ISSUE TITLE
Column right align seems not work

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#135]
`app/Actions/Fulfilment/Fulfilment/UI/IndexFulfilmentRentals.php`

```
->column(key: 'price', label: __('price'), canBeHidden: false, sortable: true, searchable: true, type: 'number')
```

![Screenshot 2024-04-26 at 10 32 53](https://github.com/inikoo/aiku/assets/8298090/21c14acf-0410-420f-86b5-122ce0d25f2f)

**Comment by aqordeon** [comment]
@inikoo now you can add `className` to make you easy put the class

> ->column(key: 'price', label: __('price'), canBeHidden: false, sortable: true, searchable: true, className: 'text-right font-mono')
