### ISSUE TITLE
Rental Agreement UI

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#147]
There is several issues with this component
![Screenshot 2024-04-28 at 14 42 00](https://github.com/inikoo/aiku/assets/8298090/a8da72ce-e482-4b3b-a8c5-46abce792bd9)

- correct currency,  and use currency format (pinia)
- Discounts don't change when price change
- Price don't change when discount is inputed
- That agreed price extra column can be. removed if the UI interaction is done properly
- Selecting multiple items don't seems to work (is not post select action)
- User  can add unlimited number of items even if is only 6 rentals
- text color black 
- when saved it saves as draft (that should be an option)

This changes need to be done:

- [x] Create component EditablePercentage.vue.
- [x] Create component EditableCurrencyAmount.vue.
- [x] Create component SyncEditablePercentageCurrencyAmount.vue. where chenge in one input change the value of the other
- [x] When saving have a button like below where use can choose to save as Active or Draft. (draft 2nd choice)

![Screenshot 2024-04-28 at 17 49 16](https://github.com/inikoo/aiku/assets/8298090/b02bcf39-5863-4042-851c-c0d35eabc094)

- [x] Clicking [Show all rentals] now (Put al rentals) a normal table should be shown , instead of delete should be a reset id prices is changed
- [x] Need to be 3 tabs Rentals, Services. Physical Goods

**Comment by YudhistiraA** [comment]
from issue #115

**Comment by aqordeon** [comment]
@inikoo what do you mean by `3 tabs Rentals, Services. Physical Goods`. does a Tab to select the Rental table? Are the Rentals, Services, and Physical Goods is stand-alone or they related to each other?
