### ISSUE TITLE
Actions called from Retina (create new action or make sure retina user can only edit what is supposed to)

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#152]
This apply to all actions call rom a retina route

Example:  `UpdatePalletDelivery`
this action edit 
```
  'customer_notes'=> ['sometimes','nullable','string','max:4000'],
  'public_notes'  => ['sometimes','nullable','string','max:4000'],
  'internal_notes'=> ['sometimes','nullable','string','max:4000'],
```

but retina user do not have permision to edit or even see `public_notes` `internal_notes`

the easier solution is create 

- [ ] New actions for retina e.g. UpdatePalletDeliveryFromRetina. where only customer_notes is on the rules method

note the are more actions where this apply, we need to find them and review what to do in each case

**Comment by itzArtha** [comment]
I've created action before, and u said use only one action
