### ISSUE TITLE
Employee attendance (Timesheet model )

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#153]
Aurora: #145 

- [x] #154
- [x] #155

Have a look in aurora and implement this

- [x] #277
- [x] #278
- [x] #161
- [x] #276

**Comment by aqordeon** [comment]
![image](https://github.com/inikoo/aiku/assets/41112717/d2608957-6b8e-4639-bbe7-370d23f700ae)

does the Interval look like this? ytd, wtd, tdy, etc.. 

@inikoo

**Comment by inikoo** [comment]
> ![image](https://private-user-images.githubusercontent.com/41112717/329983108-d2608957-6b8e-4639-bbe7-370d23f700ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTYxNzEsIm5iZiI6MTcxNTg1NTg3MSwicGF0aCI6Ii80MTExMjcxNy8zMjk5ODMxMDgtZDI2MDg5NTctNmI4ZS00NjM5LWJiZTctMzcwZDIzZjcwMGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNWNiMTU1Y2EyNWY1Zjk0OTA0YWU5MTZiYTc0MzczYTkwNGJiMDFlN2FjN2E0OTY3MzE3Y2UzNTAzY2I4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqzWl1dSOcvPFOaDw6pxgPRMN-7gznYc-Tc2-BxWsa0)
> 
> does the Interval look like this? ytd, wtd, tdy, etc..
> 
> @inikoo

No really, thi sis a navigation with 2 options (for now). Week, Month. , whre it will show all timesheets for that week/month and navigate to the previous week or month
