### ISSUE TITLE
Manufacturing navigation

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#199]
@aqordeon this is similar to warehouses navigation, but now the  object is `production`
is unlikely they will have more than 1 production (same as for warehouses) but need to be supported just in case,
this left panel navigations must have a border similar to shops one

![Screenshot 2024-05-06 at 20 33 36](https://github.com/inikoo/aiku/assets/8298090/627e1732-0476-4a0f-b969-6b5871859275)

**Comment by aqordeon** [comment]
@inikoo I don't get it. Could you explain it more detail?

**Comment by inikoo** [comment]
@aqordeon  This navigation is same as the left bar / (top bar) Warehouse navigation , just replace warehouse -> production

**Comment by aqordeon** [comment]
> this left panel navigations must have a border similar to shops one

what do you mean by border similar to shops one? does the user able to move to another Production by using arrow? or how?

@inikoo

**Comment by inikoo** [comment]
@aqordeon yes you can do that, but for now i will restrict that is only one Production per organisation, so it that inter--production navigation may never be used (you can skip it)

So work on it pls

Currently looks weird, Productions need to be hidden , and the other 2 need to borderred with the header production name similar to the shops stuff 

![Screenshot 2024-05-14 at 19 25 39](https://github.com/inikoo/aiku/assets/8298090/a422025b-1f76-4130-b012-5d378eeb2da2)

**Comment by aqordeon** [comment]
Completed on #273
