### ISSUE TITLE
RawMaterial model + actions

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#202]
use branch manufacturing

need to create:

`artisan make:model Manufacturing/RawMaterial -m `
will create
- [x] app/Models/Manufacturing/RawMaterial
- [x] create_raw_materials_table ..
base in the following columns, but use laravel/aiku like field names
![Screenshot 2024-05-06 at 18 02 27](https://github.com/inikoo/aiku/assets/8298090/842df10e-0d09-46d5-a45d-e80e6c5292bc)

create following actions:

- [x] StoreRawMaterial
- [x] UpdateRawMaterial
- [x] Create hydrators / add stats fields in GroupManufacureStats,OrganisationManufacureStats, ProductionStats
- [x] #275
- [x] ShowRawMaterial
- [x] CreateRawMaterial
- [x] EditRawMaterial
- [x] #211 
- [x] #296

**Comment by KirinZero0** [comment]
![image](https://github.com/inikoo/aiku/assets/106320231/ccb60ae2-fef7-40ce-ad97-b41226d53cb8)

**Comment by inikoo** [comment]
@KirinZero0 i add 4 new tasks for this issue related to UI stuff, you may need #199
