### ISSUE TITLE
ManufactureTask model + actions

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#203]
Same steps as in  #202  but now fro ManufactureTask model

Each ManufacturedStock #206   can have one or more ManufactureTask associated to it , and a ManufactureTask can be associated to more than 1 ManufactureProducts, so this is a Many to many relationship

- [x] ManufactureTask model + actions +hydrators etc...
- [x]  manufactured_stock_manufacture_task. Pivot table + model

![Screenshot 2024-05-06 at 18 16 46](https://github.com/inikoo/aiku/assets/8298090/34ab3767-9238-43ae-bce6-0c615967b0b2)

**Comment by KirinZero0** [comment]
![image](https://github.com/inikoo/aiku/assets/106320231/4d8979a4-fb72-4223-8d94-86317342a93f)

Manufacture Task Model, Actions, and Hydrators passed testing
