### ISSUE TITLE
Page: Shops some adjustment

### ISSUE THREAD

**Issue by aqordeon** [inikoo/aiku#212]
FE:
- [x] Shops: new column 'state' that tells the shop is open or closed
- [x] Shops: column 'name', linestroke if 'closed'

BE:
- [x] Shops: Table filter element 'open' & 'closed'
- [x] Shops: Table search

**Comment by itzArtha** [comment]
![image](https://github.com/inikoo/aiku/assets/67823902/eb58e0e0-6eff-4594-bf63-e5960591c028)
