### ISSUE TITLE
ShowPallet

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#288]
To reproduce go to [Fulfilment customer list](http://app.aiku.test/org/aw/fulfilments/awf/customers/
) choose a customer with pallets , pallets tab, and click in a pallet

- [x] **Bug** 🐞 is click in Stored items tab FE breaks
- If applicable need info about the pallet delivery / pallet return.

BE:
- [x] Prev/Next need to be implemented in ShowPallet. (note that it must be a function of the $this-parent)
- [x] Edit button is missing (for now can only edit reference and customer reference and notes)
- [x] Location need to be a link if user has permission to see warehouse "locations.{$this->warehouse->id}.view". where the warehouse can be find in the pallets.warehouse_id. (tell FE if it's done)
- [x] PageHeading: Add icon Status/State icons on the right

FE:
- [x] Remove slug (that is not for users)
- [x] Notes are missing, notes need to be in the top of the page, similar as the component used in PalletDelivery
- [x] Change label: Customer name to customer, and show Customer name <- with a link to the customer
- [x]  Change label: Customer reference is the reference the customer gave to this pallet, change label to **Customer's pallet reference** current label is can cuase confusion , users might think is the customer reference (customer ID) 
- [x] Combine State and Status in a clever way (state is a subdivsion of a status). as @inikoo if not underestand

- [x] #355

<img width="868" alt="Screenshot 2024-05-19 at 11 31 29" src="https://github.com/inikoo/aiku/assets/8298090/2d1c749b-ad69-4ff9-b2c3-946708958a51">

### in heading:

FE:
- [x] Hover over the pallet icon should show tooltip _Pallet_
- [x] Pallet reference can not be capitalized by FE
- [x] next to Pallet reference , we need to show customer_reference in brackets  e.g. (128) but not on bold so need to be other element pass to PaheHeading call it  subtittle.

<img width="350" alt="Screenshot 2024-05-19 at 11 43 50" src="https://github.com/inikoo/aiku/assets/8298090/5332b7c1-945b-4ac4-ab47-84899f15ca42">

### UI 

- [x] to much horizontal space between the data make it a little bit more compact

### Maya

- [x] @YudhistiraA confirm here that you can scan this barcode with the app, and then you can do something useful about it in the app

**Comment by aqordeon** [comment]
it's no point to show Customer Name, right? Because the data is already inside the Customer navigation @inikoo

**Comment by inikoo** [comment]
> it's no point to show Customer Name, right? Because the data is already inside the Customer navigation @inikoo

Leave the customer name, is ok, but a link on it to the customer, this view can be shown in warehouses section too,
the problem is that the link to the customer is conditional if user has permission to see customers or not
