### ISSUE TITLE
Set as damaged / Lost pallet in a more compact way

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#295]
Instead of this:
<img width="265" alt="Screenshot 2024-05-20 at 08 32 24" src="https://github.com/inikoo/aiku/assets/8298090/d679f1b5-4503-422e-9c67-196bdea3356a">

that is taking to much space and is repeated every single row, have a single icon that will show a modal

![image](https://github.com/inikoo/aiku/assets/8298090/605e2e92-e78b-4884-a360-40750eaa0d75)

note that user should write something about the incident in the text area to be able to save it

@itzArtha is a field in pallets called `incident_report` that text should be saved there like:

```
[
 [
  'type'=>'lost',
  'message'=>xxx xxx xx
  'reporter_id'=>request()->user()->id
  'date'=>now()
 ]
]
```

**Comment by itzArtha** [comment]
ok ok
