### ISSUE TITLE
Pallet Delivery: pallet count

### ISSUE THREAD

**Issue by aqordeon** [inikoo/aiku#357]
`http://app.aiku.test/org/aw/fulfilments/awf/customers/3b-recycling-ltd/pallet-deliveries/brl-002?tab=pallets`

![image](https://github.com/inikoo/aiku/assets/41112717/d21d8411-89ec-40d1-a47e-e7d3c4a10d89)

inf file:
`app/Http/Resources/Fulfilment/PalletDeliveryResource.php`
```
'number_pallets'          => $palletDelivery->stats->number_pallets,
'number_services'         => $palletDelivery->stats->number_services,
'number_physical_goods'   => $palletDelivery->stats->number_physical_goods,
 ```

**Comment by KirinZero0** [comment]
run `php artisan horizon` brah
