### ISSUE TITLE
WebpageWorkshop.vue

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#374]
Create the webpage workshop, will not be grape but our own

http://app.aiku.test/org/aw/shops/uk/websites/aw/webpages/storefront

<img width="1198" alt="Screenshot 2024-06-03 at 23 42 48" src="https://github.com/inikoo/aiku/assets/8298090/0a15ce4c-fab1-4434-9796-09631bf95cb4">

**Comment by YudhistiraA** [comment]
related to  #123
