### ISSUE TITLE
Pallet Delivery: Rental Agreement status

### ISSUE THREAD

**Issue by aqordeon** [inikoo/aiku#493]
`/Grp/FulfilmentCustomerShowcase.vue` have `data.rental_agreement.stats`

but `app/Actions/Fulfilment/FulfilmentCustomer/ShowFulfilmentCustomer.php` $fulfilmentCustomer->status is no_rental_agreement

**Comment by KirinZero0** [comment]
the problem is in the hydrator , the hydrator doesnt seem to work when creating that one rental agreement , if you encounter the same problem again just update the rental agreement, i also fixed the update action
