### ISSUE TITLE
Pallet Delivery: Retina and Aiku is not synced

### ISSUE THREAD

**Issue by aqordeon** [inikoo/aiku#533]
Retina: http://fulfilment.test/app/storage/pallet-deliveries/brl-002
Aiku: http://app.aiku.test/org/aw/fulfilments/awf/customers/3b-recycling-ltd

in Retina, there is Pallet Deliveries exist `brl-002`, but in Aiku there is no pallet deliveries exist for that customer

**Comment by itzArtha** [comment]
![image](https://github.com/user-attachments/assets/4b6e4229-6f1a-49a5-9bb2-8f02b6ef9594)
![image](https://github.com/user-attachments/assets/21772252-0e58-4fe9-abd7-d1c61aa4d7d1)
