### ISSUE TITLE
Group Settings

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#543]
action: EditGroup

needs to be set in left menu in group module (below Sysadmin)

<img width="611" alt="Screenshot 2024-07-13 at 01 08 06" src="https://github.com/user-attachments/assets/1718dcdc-2656-40d4-8433-642f1d1bbcf9">

**Comment by aqordeon** [comment]
@KirinZero0 group Logo is successfuly saved, but the logo is not changed in refresh

**Comment by KirinZero0** [comment]
@aqordeon run imgproxy in palladium
