### ISSUE TITLE
icons in organisation/group don't work correctly

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#660]
@aqordeon  Can you see if i sending you correct info from BA, no tlet me know and i will fix it

<img width="194" alt="Screenshot 2024-07-24 at 04 12 21" src="https://github.com/user-attachments/assets/3f8d9ae2-2f87-41a0-abaf-1a829c6488aa">
<img width="65" alt="Screenshot 2024-07-24 at 04 12 15" src="https://github.com/user-attachments/assets/faeadee8-9566-4f4a-97ee-d59fc48d0bdc">

**Comment by aqordeon** [comment]
@inikoo  The image sometimes works sometimes don't:
### State 1
![image](https://github.com/user-attachments/assets/bc5aa849-e4b1-4b7f-8c6b-6b828f5cfbf4)
![image](https://github.com/user-attachments/assets/e402c265-9364-46f6-a773-caf0f354a646)


### State 2
![image](https://github.com/user-attachments/assets/fa450cc3-f422-4263-bd30-9ee432cd5948)
![image](https://github.com/user-attachments/assets/5620111e-4947-4802-840f-ff8784f60433)
