### ISSUE TITLE
ShowOrgAgent

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#667]
move from tabs to subnavigations

subNavigation:

- [x] OrgAgent (anchor)
- [x] OrgSuppliers. (create Route) it should have 2 tabs OrgStockFamilies , OrgStocks
- [x] OrgStocks. (create Route) it should have 2 tabs OrgStockFamilies , OrgStocks
- [x] Purchase Orders. (create route)
- [x] StockDeliveries (create route)

Other
- [x] @aqordeon  Use same component esed in Customer/Fulfilment Customer for the: Name/Email.. Address
- [x] This can be made prettier ,also links missed to relevant IndexOrgSuppliers or IndexOrgProducts etc routes 
<img width="567" alt="Screenshot 2024-08-11 at 11 16 27" src="https://github.com/user-attachments/assets/d8f8c05c-ebff-4714-99c2-299d3c5ef3c6">

**Comment by aqordeon** [comment]
commit #1c64ca11334a30ca467a0e9c88bcca10e98c2243
