### ISSUE TITLE
Add tooltip to left menu items

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#7]
<img width="216" alt="Screenshot 2024-04-06 at 10 36 26" src="https://github.com/inikoo/aiku/assets/8298090/6e6d5769-c84f-4a43-a458-cb903f55abaa">

e.g. `app/Actions/UI/Grp/Layout/GetOrganisationNavigation.php`

```
            $navigation['reports'] = [
                'label' => __('Reports'),
                'tooltip' => __('Business Intelligence'),
```

**Comment by inikoo** [comment]
We need to check if is not to annoying for user,  maybe adjust some delay

**Comment by aqordeon** [comment]
I added a delay 500ms when the sidebar was expanded, 100ms when collapsed
