### ISSUE TITLE
Update Fulfilment Customer Problem (Cant Delete Phone number)

### ISSUE THREAD

**Issue by KirinZero0** [inikoo/aiku#722]
We cant delete phone number because if we input no data or blanks , it has no payload in it , so it wont update the phone number

![image](https://github.com/user-attachments/assets/f3096908-82fb-4579-a680-e7b4ac62dcdb)

**Comment by aqordeon** [comment]
commit: 6b050593e93ea1c520054b429607950cc6fc8512
