### ISSUE TITLE
Support for organisation.type=DIGITAL_AGENCY in the navigaton

### ISSUE THREAD

**Issue by inikoo** [inikoo/aiku#80]
![Screenshot 2024-04-11 at 15 35 34](https://github.com/inikoo/aiku/assets/8298090/c3d097c5-0b0e-414b-aaa8-f473291ff6cb)

**Comment by aqordeon** [comment]
I don't get it, can you elaborate more about it?

**Comment by inikoo** [comment]
@aqordeon is similar at what was done with agency, digital_agency is other type of organisation

**Comment by aqordeon** [comment]
duplicated #282
